# Generated by Django 2.0.7 on 2018-09-08 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intro', '0004_auto_20180908_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('publish', models.BooleanField(default=True)),
                ('type', models.CharField(blank=True, choices=[('Notice', 'Notice'), ('Announcement', 'Announcement'), ('other', 'Other')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField(blank=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='intro.Profile')),
            ],
            options={
                'ordering': ['creationDate'],
            },
        ),
    ]
